### PR TITLE
Fixed sorting and archive filters in collections [#1239]

### LINKED ISSUE #1239: Collections do not honor the sort selected.
**Describe The Bug**
When viewing a collection (publisher, series, etc.) the comics are not sorting, and the sort field is not being pre-filled with the user's preference. The same with the archive type selection.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Go to the library page.
1. Select a sort and archive type.
1. Now go to any collection, such as series.
  * The sort and archive types are not preselected.
1. Select a sort or an archive type.
  * Nothing happens.

**Expected Behavior**
1. The comics should be filtered and sorted as selected.
1. The dropdown fields should be prefilled with the user's choices when the page reloads.

### PR DESCRIPTION
**Pull request by mcpierce**
Closes #1239 

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: comixed-webui/src/app/collections/pages/collection-detail/collection-detail.component.ts [hunk 1]
```diff
@@ -108,6 +118,26 @@ export class CollectionDetailComponent implements OnInit, OnDestroy {
...
+            case ArchiveType.CB7:
+              this.archiveTypeFilter = ArchiveType.CB7;
+              break;
+            default:
+              this.archiveTypeFilter = null;
+          }
+        } else {
+          this.logger.debug('Resetting archive type filter');
+          this.archiveTypeFilter = null;
+        }
```
Comment (BRUCELLA2) [inline comixed-webui/src/app/collections/pages/collection-detail/collection-detail.component.ts]: I wonder if something like this could be more concise and reduce the number of duplicated lines (but i'm not sure that the performance are not altered) :
          if (new Set([ArchiveType.CBZ, ArchiveType.CBR, ArchiveType.CB7]).has(archiveType)) {
            this.archiveTypeFilter = archiveType;
          } else {
            this.archiveTypeFilter = null;
          }

**Review by BRUCELLA2 — COMMENTED** [review]
it's ok but just one question :)

File: comixed-webui/src/app/collections/pages/collection-detail/collection-detail.component.ts (hunk 1 above)
Comment (mcpierce) [reply comixed-webui/src/app/collections/pages/collection-detail/collection-detail.component.ts]: I think your suggestion is a good one. I'll implement it tonight and update the PR.

Comment (mcpierce) [reply comixed-webui/src/app/collections/pages/collection-detail/collection-detail.component.ts]: Pushed the updated code. I removed that code, plus the same check in another spot, since there was an existing method to look for the archive type from a string.

**Review by BRUCELLA2 — APPROVED** [review]
