### PR TITLE
Fixed when consolidating a comic to its current filename [#1241]

### LINKED ISSUE #1241: Consolidating the library results in comics all having "*-1.cb?" in their filenames.
**Describe The Bug**
When consolidating the library, comic files are having "-1" added to their base filename, even when there is no duplicate comic file in the library.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Consolidate the library.
1. Look for any comic that definitely does not have a duplicate.
1. The filename will have "-1" appended to the filename.

**Expected Behavior**
1. The filename should not have a marker of it being a duplicate.

### PR DESCRIPTION
**Pull request by mcpierce**
Closes #1241 

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: comixed-adaptors/src/test/java/org/comixedproject/adaptors/comicbooks/ComicFileAdaptorTest.java [hunk 1]
```diff
@@ -292,14 +293,27 @@ public void testIsComicFileForCB7() {
...
 
+  @Test
+  public void testFindAvailableWithOriginalFilename() {
+    final String result =
+        adaptor.findAvailableFilename(
+            TEST_ORIGINAL_FILENAME, "src/test/resources/example", 0, "cbz");
+
+    assertEquals("src/test/resources/example-2.cbz", result);
+  }
+
```
Comment (BRUCELLA2) [inline comixed-adaptors/src/test/java/org/comixedproject/adaptors/comicbooks/ComicFileAdaptorTest.java]: this test find available filename with original filename ?

**Review by BRUCELLA2 — CHANGES_REQUESTED** [review]

File: comixed-adaptors/src/test/java/org/comixedproject/adaptors/comicbooks/ComicFileAdaptorTest.java (hunk 1 above)
Comment (mcpierce) [reply comixed-adaptors/src/test/java/org/comixedproject/adaptors/comicbooks/ComicFileAdaptorTest.java]: The test name? I guess it should be named "...WithOriginalFilenameUsed()" instead.

Comment (BRUCELLA2) [reply comixed-adaptors/src/test/java/org/comixedproject/adaptors/comicbooks/ComicFileAdaptorTest.java]: I ask because this part of the code is not covered. 
if (file.exists() && StringUtils.pathEquals(originalFilename, candidate)) {
      log.debug("Using original filename: {}", originalFilename);
      return originalFilename;
}

I was wondering if it was an error in the test or a test oversight :)

Comment (mcpierce) [reply comixed-adaptors/src/test/java/org/comixedproject/adaptors/comicbooks/ComicFileAdaptorTest.java]: I've fixed the tests to make sure it covers this scenario and pushed the update.

**Review by BRUCELLA2 — APPROVED** [review]
