### PR TITLE
Changed where and when the persisted task is deleted [#487]

### LINKED ISSUE #487: The persisted Task entry should not be removed until the task completes
**Describe the bug**
If one starts importing comics and then restarts the server, any comic that was in the midst of being processed is left in an in-between state; ie, it has no ComicFileDetails associated with it, but there are no tasks enqueued to process it. This is because the task running system deletes the record from the tasks table before the task itself completes running. Instead, the entire thing should be handled in a single transaction: 

1. Load the **tasks** entry.
1. Rehydrate the task.
1. Execute the task.
1. Delete the entry from the **tasks** table.

### PR DESCRIPTION
**Pull request by mcpierce**
## Status
**READY**

## Migrations
NO

## Description
Previously, the persisted task was deleted from the database when it was
decoded and before it was enqueued.

Now the persisted task, along with the executable one, is given to the
TaskManager. When the executable task completes then the persisted one
is removed from the database.

### CODE REVIEW

File: comixed-tasks/src/main/java/org/comixedproject/task/model/DeleteComicWorkerTask.java [hunk 1]
```diff
@@ -44,12 +46,8 @@
   @Autowired private ComicService comicService;
   @Autowired private ReadingListService readingListService;
 
-  private boolean deleteFile;
-  private Comic comic;
-
-  public void setDeleteFile(boolean deleteFile) {
-    this.deleteFile = deleteFile;
-  }
+  @Getter @Setter private Boolean deleteFile;
```
Comment (BRUCELLA2) [inline comixed-tasks/src/main/java/org/comixedproject/task/model/DeleteComicWorkerTask.java:49]: Is the change from boolean to boolean intentional?

File: comixed-tasks/src/main/java/org/comixedproject/task/runner/TaskManager.java [hunk 2]
```diff
@@ -43,26 +44,45 @@
...
           }
         });
   }
 
+  /**
+   * Enqueue and execute the given task.
+   *
+   * @param task the task
+   */
+  public void runTask(final WorkerTask task) {
```
Comment (BRUCELLA2) [inline comixed-tasks/src/main/java/org/comixedproject/task/runner/TaskManager.java]: workerTask serait mieux que task pour éviter les confusion (entre la classe WorkerTask et la class Task).

**Review by BRUCELLA2 — CHANGES_REQUESTED** [review]

File: comixed-tasks/src/main/java/org/comixedproject/task/model/DeleteComicWorkerTask.java (hunk 1 above)
Comment (mcpierce) [reply comixed-tasks/src/main/java/org/comixedproject/task/model/DeleteComicWorkerTask.java:49]: Yes. Since it's coming out of the database, I'm using the wrapper class to defensively program against the value being null.

File: comixed-tasks/src/main/java/org/comixedproject/task/runner/TaskManager.java (hunk 2 above)
Comment (mcpierce) [reply comixed-tasks/src/main/java/org/comixedproject/task/runner/TaskManager.java]: D'accord. Je l'ai renommé.

Comment (BRUCELLA2) [reply comixed-tasks/src/main/java/org/comixedproject/task/runner/TaskManager.java]: ho sorry ... I wrote in French !!!! :D 
For non French speaking people :
workerTask would be better than task to avoid confusion (between the WorkerTask class and the Task class).

**Review by BRUCELLA2 — APPROVED** [review]
