### PR TITLE
Changed the scraping note to include the adaptor name [#1186]

### LINKED ISSUE #1186: Scraping notes should mention the ComiXed app.
**Describe The Bug**
Comics previously scraped by another tool and then scraped by ComiXed still show the previous tool as the source for the metadata.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Import a comic that was previously scraped by another tool, like ComicVine Scraper.
1. Scrape the comic with ComiXed.
1. The Overview tab of the comic's details page shows "Comic details scraped by comicvine" (the remainder having been truncated).

**Expected Behavior**
1. The text should say something like "Scraped by ComiXed on $DATE".

**Screenshots**
Screen Shot 2022-03-26 at 11 17 11 AM

### PR DESCRIPTION
**Pull request by mcpierce**
Closes #1186 

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: comixed-services/src/main/java/org/comixedproject/service/metadata/MetadataService.java [hunk 1]
```diff
@@ -295,7 +295,8 @@ public Comic scrapeComic(
       log.trace("Creating comic metadata record");
       comic.setMetadataSource(
           new ComicMetadataSource(comic, metadataSource, issueDetails.getSourceId()));
-      comic.setNotes(String.format("Comic details scraped by %s", metadataAdaptor.getIdentifier()));
+      comic.setNotes(
+          String.format("Comic metadata scraped using ComiXed & %s.", metadataAdaptor.getSource()));
```
Comment (BRUCELLA2) [inline comixed-services/src/main/java/org/comixedproject/service/metadata/MetadataService.java:299]: Shouldn't translation be considered?

**Review by BRUCELLA2 — COMMENTED** [review]
It's ok with me, I just have a question about a possible improvement.

File: comixed-services/src/main/java/org/comixedproject/service/metadata/MetadataService.java (hunk 1 above)
Comment (mcpierce) [reply comixed-services/src/main/java/org/comixedproject/service/metadata/MetadataService.java:299]: I think, in a future version, we can take on server-side translations when we can get more resources to help there.

**Review by BRUCELLA2 — APPROVED** [review]
